{% set data = load_setup_py_data() %}

package:
  name: labtex
  version: {{ data.get('version') }}
  
about:
  home: {{ data['url'] }}
  license: MIT
  summary: {{ data.get('description') }}

source:
  path: ..

build:
  script: python setup.py install
  noarch: python

requirements:
  build:
    - python
    - numpy
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy 
    - matplotlib